title: Chromatic Misfit
logo: /assets/img/artist-icon-1-1200x1200.jpg
description: Producer. Songwriter. Musician.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

github:
  zip_url: https://open.spotify.com/artist/5O4l4URYQ4EqEWrbNpVXiS
  tar_url: https://www.youtube.com/@ChromaticMisfit
  repository_url: https://soundcloud.com/chromatic-misfit
